export const gameSet2 = {
  "id": 1,
  "name": "XXX room :)",
  "description": "Комната для тех, кому скучно засыпать одному...",
  "games": [
		{
			"id": 14,
			"status": "closed",
			"gamerCount": 4,
			"occupiedPlaces": 0,
			"stepsNumber": 40,
			"currentStep": 40,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1

		},
		{
			"id": 12,
			"status": "in process",
			"gamerCount": 4,
			"occupiedPlaces": 4,
			"stepsNumber": 56,
			"currentStep": 24,
			"totalFine": 150,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 23,
			"status": "open",
			"gamerCount": 3,
			"occupiedPlaces": 0,
			"stepsNumber": 69,
			"currentStep": 0,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 16,
			"status": "closed",
			"gamerCount": 5,
			"occupiedPlaces": 0,
			"stepsNumber": 74,
			"currentStep": 74,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 17,
			"status": "open",
			"gamerCount": 4,
			"occupiedPlaces": 2,
			"stepsNumber": 45,
			"currentStep": 15,
			"totalFine": 56,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 28,
			"status": "closed",
			"gamerCount": 3,
			"occupiedPlaces": 0,
			"stepsNumber": 70,
			"currentStep": 70,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 14,
			"status": "closed",
			"gamerCount": 4,
			"occupiedPlaces": 0,
			"stepsNumber": 40,
			"currentStep": 40,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1

		},
		{
			"id": 12,
			"status": "in process",
			"gamerCount": 4,
			"occupiedPlaces": 4,
			"stepsNumber": 56,
			"currentStep": 24,
			"totalFine": 150,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 23,
			"status": "open",
			"gamerCount": 3,
			"occupiedPlaces": 0,
			"stepsNumber": 69,
			"currentStep": 0,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 16,
			"status": "closed",
			"gamerCount": 5,
			"occupiedPlaces": 0,
			"stepsNumber": 74,
			"currentStep": 74,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 17,
			"status": "open",
			"gamerCount": 4,
			"occupiedPlaces": 2,
			"stepsNumber": 45,
			"currentStep": 15,
			"totalFine": 56,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 28,
			"status": "closed",
			"gamerCount": 3,
			"occupiedPlaces": 0,
			"stepsNumber": 70,
			"currentStep": 70,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 14,
			"status": "closed",
			"gamerCount": 4,
			"occupiedPlaces": 0,
			"stepsNumber": 40,
			"currentStep": 40,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1

		},
		{
			"id": 12,
			"status": "in process",
			"gamerCount": 4,
			"occupiedPlaces": 4,
			"stepsNumber": 56,
			"currentStep": 24,
			"totalFine": 150,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 23,
			"status": "open",
			"gamerCount": 3,
			"occupiedPlaces": 0,
			"stepsNumber": 69,
			"currentStep": 0,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 16,
			"status": "closed",
			"gamerCount": 5,
			"occupiedPlaces": 0,
			"stepsNumber": 74,
			"currentStep": 74,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 17,
			"status": "open",
			"gamerCount": 4,
			"occupiedPlaces": 2,
			"stepsNumber": 45,
			"currentStep": 15,
			"totalFine": 56,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		},
		{
			"id": 28,
			"status": "closed",
			"gamerCount": 3,
			"occupiedPlaces": 0,
			"stepsNumber": 70,
			"currentStep": 70,
			"totalFine": 0,
			"holdingCost": 0.5,
			"backorderCost": 1,
			"demandPattern": 1
		}
  ]
};
